### ISSUE TITLE
Problem with sw4.py

### ISSUE THREAD

**Issue by PatLub85** [lkoepsel/microserver#1]
Hi Lief,
'm trying to understand how to use Microdot.
Your tutorial seems perfect to me to achieve this.
I managed to understand sw1, sw2 and sw3.py, however I have an error with sw4.py
I'm using an ESP32, Micropython 1.21 and Microdot V2.
Here is the error I get:
```
Starting async server on 0.0.0.0:5000...
Traceback (most recent call last):
  File "microdot.py", line 1327, in dispatch_request
  File "microdot.py", line 39, in invoke_handler
  File "<stdin>", line 188, in index
  File "utemplate.py", line 44, in render
  File "templates/index4_html.py", line 81, in render
NameError: name 'leds' isn't defined
```
and index4 html.py, line 81
```
80</table>"""
81    yield from render1(leds)
82    yield """
```
Do you have any idea what is wrong?
Thanks in advance

**Comment by lkoepsel** [comment]
I'd recommend trying the following:
1. Confirm the first line in index_v4.html is:
```
{% args led_state, leds%}
```
2. The array leds contains the values so it needs to be passed in light_leds_v4.py so lines 72 and 74 need to have "leds", along with led_state
3. Sometimes the python version of index.html (in this case index4_html.py) is compiled correctly by Microdot, so its helpful to delete it and have it recompile.
4. Or the best option is to reload your code by completely deleting the code files from you ESP32 and reloading

**Comment by PatLub85** [comment]
1. OK
2.  OK
3. I deleted index4_html.py several times, but I still have the problem
4. I'll try to redo everything on another ESP32.
It's curious, sw3.py uses {% args led_state%}, and it works!

**Comment by lkoepsel** [comment]
I don't have a system to test at the moment. It also helps to look at the index4_html.py file and make sure it contains the correct code at the beginning for incorporating "leds". If I had a system, I'd provide the details...

For example, take a look at index3_html.py and see how led_state is used...in index4_html.py, both leds and led_state need to be used in a similar fashion. The error implies that leds isn't defined...

I have found many of my errors like this stem from having a partially complete system. Somehow, some of my code is version 3 and some of my code is version 4. This is why I recommend deleting all of the code base on the ESP32 and reloading it.

**Comment by PatLub85** [comment]
Hi,
I found it!
for some reason, my index4.html file started at line 2.
By deleting the empty line 1, it's ok
Thanks for helping me

**Comment by lkoepsel** [comment]
Good for you!

And thank you for advising of the problem. It will be helpful to others which might face the same problem.
